

app:
  message: Message has been sent successfully.
  name: RabbitMQ Producer Application
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: DIRECT_EXCHANGE
    queue: MQ_BUSINESS
    routingkey: RKEY_BUSINESS
server:
  port: 8081